// <auto-generated />
using System;
using EFDBFHomeBanking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFDBFHomeBanking.Migrations
{
    [DbContext(typeof(HomeBankingContext))]
    partial class HomeBankingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFDBFHomeBanking.Models.Account", b =>
                {
                    b.Property<string>("accountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("balance")
                        .HasColumnType("real");

                    b.Property<int?>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("accountId");

                    b.HasIndex("clientId");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("EFDBFHomeBanking.Models.Bank", b =>
                {
                    b.Property<int>("bankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bankId");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("EFDBFHomeBanking.Models.Client", b =>
                {
                    b.Property<int>("clientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("bankId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nroDoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clientId");

                    b.HasIndex("bankId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("EFDBFHomeBanking.Models.Movement", b =>
                {
                    b.Property<int>("movementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("value")
                        .HasColumnType("real");

                    b.HasKey("movementId");

                    b.HasIndex("accountId");

                    b.ToTable("Movement");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Movement");
                });

            modelBuilder.Entity("EFDBFHomeBanking.Models.MovementClasses.Deposit", b =>
                {
                    b.HasBaseType("EFDBFHomeBanking.Models.Movement");

                    b.HasDiscriminator().HasValue("Deposit");
                });

            modelBuilder.Entity("EFDBFHomeBanking.Models.MovementClasses.Extract", b =>
                {
                    b.HasBaseType("EFDBFHomeBanking.Models.Movement");

                    b.HasDiscriminator().HasValue("Extract");
                });

            modelBuilder.Entity("EFDBFHomeBanking.Models.MovementClasses.Transfer", b =>
                {
                    b.HasBaseType("EFDBFHomeBanking.Models.Movement");

                    b.Property<bool>("checkedDeposit")
                        .HasColumnType("bit");

                    b.Property<bool>("checkedExtraction")
                        .HasColumnType("bit");

                    b.Property<int>("originAccountId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Transfer");
                });

            modelBuilder.Entity("EFDBFHomeBanking.Models.Account", b =>
                {
                    b.HasOne("EFDBFHomeBanking.Models.Client", null)
                        .WithMany("accounts")
                        .HasForeignKey("clientId");
                });

            modelBuilder.Entity("EFDBFHomeBanking.Models.Client", b =>
                {
                    b.HasOne("EFDBFHomeBanking.Models.Bank", null)
                        .WithMany("clients")
                        .HasForeignKey("bankId");
                });

            modelBuilder.Entity("EFDBFHomeBanking.Models.Movement", b =>
                {
                    b.HasOne("EFDBFHomeBanking.Models.Account", null)
                        .WithMany("movements")
                        .HasForeignKey("accountId");
                });
#pragma warning restore 612, 618
        }
    }
}
